app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [

    path('', include(('bases.urls', 'bases'), namespace='bases')),
    # rutas de modulo componentes
    path('component/', include(('component.urls', 'component'), namespace='component')),

    # rutas del modulo ventas
    path('sales/', include(('sales.urls', 'sales'), namespace='sales')),
    # rutas para ocontenidos y videos pautas
    path('content/', include(('content.urls', 'content'), namespace='content')),
    # ruta para los reportes y envio de mails
    path('report/', include(('report.urls', 'report'), namespace='report')),
    # rutas para los reportes que se pueden imprimir
    path('reportprint/', include(('reportprint.urls',
                                  'reportprint'), namespace='reportprint')),

    # rutas para los reportes de emision de cliente y mensual general
    path('reportemision/', include(('reportemision.urls',
                                    'reportemision'), namespace='reportemision')),

    # rutas para rondas de personal en las locaciones
    path('rondas/', include(('rondas.urls', 'rondas'), namespace='rondas')),

    # rutas para mostrar vistas de reportes rapidos como clinetes por locaion spots por clientes
    path('display/', include(('display.urls', 'display'), namespace='display')),

    # rutas para mostrar vistas de reportes rapidos como clinetes por locaion spots por clientes
    path('maintenance/', include(('maintenance.urls', 'maintenance'), namespace='maintenance')),

    # rutas para mostrar todos los contratos y sus locaciones con sus respectivos spots 
    path('allviewcontract/', include(('allviewcontract.urls', 'allviewcontract'), namespace='allviewcontract')),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from .views import VideoView, VideoNew, VideoEdit, VideoForm, video_delete, video_disabled, \
    playlist_list, playlist_generator, playlist_order, playlist_new, playlist_view, playlist_delete, \
    playlist_order_2, \
    playlist_generator2, playlist_reorder, playlist_edit_date, playlist_proyection, \
    DriveView, DriveNew, DriveEdit, drive_delete

urlpatterns = [
    # vistas para videos
    path('videos/', VideoView.as_view(), name='videos_list'),
    path('videos/new', VideoNew.as_view(), name='video_new'),

    path('videos/edit/<int:pk>',
         VideoEdit.as_view(), name='video_edit'),
    path('videos/disabled/<int:id>', video_disabled, name='video_disabled'),
    path('videos/delete/<int:id>', video_delete, name='video_delete'),



    # rutas para videos
    path('playlist/', playlist_list, name='playlist_list'),
    path('playlist/generator', playlist_generator, name='playlist_generator'),
    path('playlist/generator/hand', playlist_generator2, name='playlist_generator_hand'),

    path('playlist/contract_list/', playlist_generator, name='playlist_contract_list'),
    path('playlist/delete/<int:id>', playlist_delete, name='playlist_delete'),
    path('playlist/proyection/<int:id>', playlist_proyection, name='playlist_proyection'),



    path('playlist/generator/order/', playlist_order, name='playlist_order'),
    path('playlist/new', playlist_new, name='playlist_new'),

    path('playlist/view/<int:id>', playlist_view, name='playlist_view'),
    # playlist_edit_date manejado por ajax
    path('playlist/edit_date', playlist_edit_date, name='playlist_edit_date'),

    
    path('playlist/generator/order_2/', playlist_order_2, name='playlist_order_2'),

    path('playlist/generator/reorder/', playlist_reorder, name='playlist_reorder'),


    # para adminidtrar las ruts a google /drive
    path('drive/',DriveView.as_view(), name='drive_list'),
    path('drive/new',DriveNew.as_view(), name='drive_new'),
    path('drive/edit/<int:pk>',DriveEdit.as_view(), name='drive_edit'),
    path('drive/delete/<int:id>',drive_delete, name='drive_delete'),

]

reportprint/urls.py
from django.urls import path
from .views import  report_contract, report_playlist, report_playlist_xls

urlpatterns = [
    # vistas para ventas
    path('report_contract/<int:id>',report_contract, name='report_contract'),

    path('report_platlist/<int:id>',report_playlist, name='report_playlist'),

    path('report_playlist_xls/<int:id>',report_playlist_xls, name='report_playlist_xls'),

    
    
]

bases/models.py
from django.db import models

from django.contrib.auth.models import User

class ClassModel(models.Model):
    state = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_created = models.ForeignKey(User, on_delete=models.CASCADE)
    user_updated = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract=True

content/models.py
from django.db import models

from bases.models import ClassModel
from sales.models import Contract, Order
from component.models import Product, City
# Create your models here.
 

class Video(ClassModel):
    name = models.CharField(max_length=100)
    duration = models.TimeField()
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    description = models.CharField(max_length=100, null=True, blank=True)
    img = models.ImageField(upload_to='videos', null=True, blank=True)
    video = models.FileField(upload_to='videos', null=True, blank=True)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)

    def __str__(self):
        
        return '{}:{}'.format(self.name, self.duration)

    def duration_all(self):
        duration = str(self.duration)
        return duration

    def duration_seconds(self):
        t = self.duration
        seconds = (t.hour * 60 + t.minute) * 60 + t.second
        
        # print(type(seconds)) 
        return seconds


class Playlist(ClassModel):
    create_date = models.DateField(null=False, blank=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    proyection = models.BooleanField(default=False, null=False, blank=False)
    
    def __str__(self):
        return '{} del {} '.format(self.product, self.create_date)

class Playlist_spot_detail(ClassModel):
    repeat_count = models.IntegerField(null=False, blank=False)
    time_total = models.IntegerField(null=False, blank=False)
    porcentage = models.FloatField(null=False, blank=False)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

class Playlist_client_detail(ClassModel):
    time_total = models.IntegerField(null=False, blank=False)
    pauta_loop = models.FloatField(null=False, blank=False)
    second_total = models.IntegerField(null=False, blank=False)
    time_contract = models.IntegerField(null=False, blank=False)
    time_bonification = models.IntegerField(null=False, blank=False)

    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)


class Playlist_document(ClassModel):
    order_list = models.IntegerField(null=False, blank=False)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)


class Drive_urls(ClassModel):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    info = models.CharField(max_length=20, null=True, blank=True)
    url = models.CharField(max_length=500, null=False, blank=False)
    

content/views.py
from django.shortcuts import render

from django.views import generic
from django.urls import reverse_lazy

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin


# importacion pra la vista basada en funciones
from django.contrib.auth.decorators import login_required, permission_required

from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.http import HttpResponse
import json

from .models import Video, Playlist, Playlist_client_detail, Playlist_spot_detail, Playlist_document, Drive_urls
from .forms import VideoForm, DriveForm

from bases.views import SinPrivilegios

from component.models import Product
from sales.models import Contract, Order

import math

import datetime

# vistas para Categorias
# TODO: completar los privilegios de los usuarios para cada vista


class VideoView(SinPrivilegios,
                generic.ListView):
    # este permision_required es nesesario para ver el tema de permisos a nivel de vista
    permission_required = 'content.view_video'
    model = Video
    template_name = 'content/video_view.html'
    context_object_name = 'obj'


class VideoNew(SuccessMessageMixin, LoginRequiredMixin, generic.CreateView):
    model = Video
    template_name = 'content/video_form.html'
    context_object_name = 'obj'
    form_class = VideoForm
    success_url = reverse_lazy('content:videos_list')
    login_url = 'bases:login'
    success_message = "Creado satisfactoriamente"

    def form_valid(self, form):
        form.instance.user_created = self.request.user

        return super().form_valid(form)


class VideoEdit(SuccessMessageMixin, LoginRequiredMixin, generic.UpdateView):
    model = Video
    template_name = 'content/video_form.html'
    context_object_name = 'obj'
    form_class = VideoForm
    success_url = reverse_lazy('content:videos_list')
    login_url = 'bases:login'
    success_message = "Actializado satisfactoriamente"

    def form_valid(self, form):
        form.instance.user_updated = self.request.user.id

        return super().form_valid(form)


@login_required(login_url='/login/')
@permission_required('content.disabled_video', login_url='bases:sin_privilegios')
def video_disabled(request, id):
    template_name = 'content/video_disabled.html'
    contexto = {}
    cat = Video.objects.filter(pk=id).first()

    if not cat:
        return HttpResponse('Video no existe' + str(id))

    if request.method == 'GET':
        contexto = {'obj': cat}

    if request.method == 'POST':
        cat.state = False
        cat.save()
        # mensaje par que la vista lo muestre sin coloca en comentarios pues al momento de los esta haciendo con ajax
        # messages.success(request, 'Se inactivo correctamente')

        contexto = {'obj': 'OK'}
        return HttpResponse('Video  Inactivada')

    return render(request, template_name, contexto)



@login_required(login_url='/login/')
@permission_required('content.delete_video', login_url='bases:sin_privilegios')
def video_delete(request, id):
    template_name = 'content/video_delete.html'
    contexto = {}
    cat = Video.objects.filter(pk=id).first()

    if not cat:
        return HttpResponse('Video no existe' + str(id))

    if request.method == 'GET':
        contexto = {'obj': cat}

    if request.method == 'POST':
        # cat.state = False
        cat.delete()
        # mensaje par que la vista lo muestre sin coloca en comentarios pues al momento de los esta haciendo con ajax
        # messages.success(request, 'Se inactivo correctamente')

        contexto = {'obj': 'OK'}
        return HttpResponse('Video  borrado')

    return render(request, template_name, contexto)


# ==========================================================
# para manejar listas de reproduccion
# ==========================================================

@login_required(login_url='/login/')
@permission_required('content.delete_playlist', login_url='bases:sin_privilegios')
def playlist_delete(request, id):
    template_name = 'content/playlist_delete.html'
    contexto = {}
    cat = Playlist.objects.filter(pk=id).first()

    if not cat:
        return HttpResponse('Playlist no existe' + str(id))

    if request.method == 'GET':
        contexto = {'obj': cat}

    if request.method == 'POST':
        # cat.state = False
        cat.delete()
        # mensaje par que la vista lo muestre sin coloca en comentarios pues al momento de los esta haciendo con ajax
        # messages.success(request, 'Se inactivo correctamente')

        contexto = {'obj': 'OK'}
        return HttpResponse('Playlist  borrado')

    return render(request, template_name, contexto)



def playlist_list(request):
    contexto = {}
    template_name = 'content/playlist_list.html'
    if request.method == 'GET':
        playlist = Playlist.objects.all()
        contexto = {'obj': playlist}

    return render(request, template_name, contexto)


def playlist_view(request, id):
    contexto = {}
    template_name = 'content/playlist_list.html'
    if request.method == 'GET':
        playlist = Playlist.objects.filter(id=id).first()
        pl = list(map(list, playlist.clients_g))
        # pls = json.loads(pl)
        print(pl)
        print(type(pl))

    return render(request, template_name, contexto)



def playlist_edit_date(request):
    
    id = request.POST.get('id')
    date_new = request.POST.get('date_new')

    print(request.POST)
    playlist = Playlist.objects.get(pk=id)

    if not playlist:
        return HttpResponse('false')

    

    if request.method == 'POST':
        date_new = datetime.datetime.strptime(date_new, "%Y-%m-%d").date()
        playlist.create_date = date_new
        playlist.save()
        # mensaje par que la vista lo muestre sin coloca en comentarios pues al momento de los esta haciendo con ajax
        # messages.success(request, 'Se inactivo correctamente')

        
        return HttpResponse('ok')

    return HttpResponse('false')

def playlist_generator(request):
    contexto = {}
    template_name = 'content/playlist_form.html'

    if request.method == 'GET':
        product = Product.objects.filter(state=1).all()
        today = datetime.datetime.now()
        contexto = {'obj': product, 'today': today}

    if request.method == 'POST':

        id_product = request.POST.get("id_product")
        old_playlist = Playlist.objects.filter(product=id_product).last()
        old_doc = Playlist_spot_detail.objects.filter(playlist=old_playlist.id).all()
        old_aux = []
        for item in old_doc:
            old_aux.append(item.video.id)

        check = ''
        # print(old_doc)
        order = Order.objects.filter(product_id=id_product, state=1).all().order_by('-contract__auspice')
        # print(order)
        lista_order_json = []
        for item in order:
            # print(item.contract.id)
            videos = Video.objects.all().filter(contract_id=item.contract.id, state=True)
            for video in videos:
                
                # print(video)
                objeto_order = {}
                objeto_order["id"] = item.id
                objeto_order["pass"] = item.pass_contract
                objeto_order["porcentage"] = item.porcentage_contract
                objeto_order["contract"] = item.contract.client.name + " desde " + \
                    str(item.contract.start_date) + \
                    " al " + str(item.contract.end_date)
                objeto_order["description"] = item.description
                objeto_order["video_id"] = video.id
                objeto_order["video_name"] = video.name
                objeto_order["video_duration"] = video.duration_all()
                # Se deberia asignar al dictionary todos los atributos que desee enviar en el json.
                if video.id in old_aux:
                    check = 'checked'
                    print(video.name)
                objeto_order["if_check"] = check
                lista_order_json.append(objeto_order)
                check = ''
        # print(lista_order_json)

        contexto = {'obj': 'OK', 'order': lista_order_json}
        return HttpResponse(json.dumps(contexto), content_type=json)

        # return HttpResponse('ok')

    return render(request, template_name, contexto)
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# no esta funcionando
# ================================================================================================================
def playlist_generator2(request):
    contexto = {}
    template_name = 'content/playlist_form_hand.html'

    if request.method == 'GET':
        product = Product.objects.filter(state=1).all()
        today = datetime.datetime.now()
        contexto = {'obj': product, 'today': today}

    if request.method == 'POST':

        id_product = request.POST.get("id_product")

        # old_playlist = Playlist.objects.filter(product=id_product).last()
        # print(old_playlist)
        order = Order.objects.filter(product_id=id_product, state=1).all().order_by('-contract__auspice')
        # print(order)
        lista_order_json = []
        for item in order: 
            # print(item.contract.id)
            videos = Video.objects.all().filter(contract_id=item.contract.id, state=True)
            for video in videos:

                # print(video)
                objeto_order = {}
                objeto_order["id"] = item.id
                objeto_order["pass"] = item.pass_contract
                objeto_order["porcentage"] = item.porcentage_contract
                objeto_order["contract"] = item.contract.client.name + " desde " + \
                    str(item.contract.start_date) + \
                    " al " + str(item.contract.end_date)
                objeto_order["description"] = item.description
                objeto_order["video_id"] = video.id
                objeto_order["video_name"] = video.name

content/templates/content/drive_form.html
{% extends 'base/base.html' %}

{% block page_content %}

<form method="POST" class="form-group" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="col-xl-8 col-md-8 mb-8">

        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
            {% else %}

            <div class="card border-left-primary shadow h-100 py-2">
                {% endif %}

                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nuevo {% endif %} enlace
                            </div>
                            <small class="text-danger">
                                {% if form.errors %}
                                {% for field in form %}
                                {% if field.errors %}
                                {% for error in field.errors %}
                                {{ error|escape }}
                                {% endfor %}
                                {% endif %}
                                {% endfor %}

                                {% if form.non_field_errors%}
                                {% for error in form.non_field_errors %}
                                {{ error|escape }}
                                {% endfor %}
                                {% endif %}
                                {% endif %}
                            </small>
                            <div class="dropdown-divider"></div>
                            <!--  -->
                            <div class="form-group row">
                                <label for="id_name" class="col-sm-2 col-form-label">Nombre</label>
                                <div class="col-sm-10 ">
                                    {{form.city}}
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="id_info" class="col-sm-2 col-form-label">Info</label>
                                <div class="col-sm-10">
                                    <input type="text" name="info" maxlength="100" class="form-control"
                                        id="id_info" value="{% if obj %} {{obj.info}} {% endif %}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_url" class="col-sm-2 col-form-label">Url</label>
                                <div class="col-sm-10">
                                    <input type="text" name="url" maxlength="100" class="form-control"
                                        id="id_url" value="{% if obj %} {{obj.url}} {% endif %}">
                                </div>
                            </div>

                            
                            <div class="form-group row">
                                <div class="col-sm-2">Estado</div>
                                <div class="col-sm-10">
                                    <div class="form-check">
                                        <input type="checkbox" name="state" class="form-check-input" {% if obj.state %}
                                            checked {% endif %} id="id_state">
                                        <label class="form-check-label" for="id_state">
                                            Marcar estado.
                                        </label>
                                    </div>

                                </div>
                            </div>


                            <!--  -->


                            <!-- {{form.as_p}} -->
                            <div class="dropdown-divider"></div>
                            <div class="form-group row text-center">
                                <div class="col-sm-10">
                                    <a href="{% url 'content:drive_list' %}" class="btn btn-danger"><span
                                            class="fa fa-undo"> Cancelar</span></a>
                                    <button type="submit" class="btn btn-success"><span class="fa fa-save"></span>
                                        Guardar</button>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>

</form>

{% endblock %}
{% block js_page %}
{% endblock %}

content/templates/content/video_form.html
{% extends 'base/base.html' %}

{% block page_content %}

<form method="POST" class="form-group" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="col-xl-12 col-md-12 mb-12">

        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
            {% else %}

            <div class="card border-left-primary shadow h-100 py-2">
                {% endif %}

                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nuevo {% endif %} Video
                            </div>
                            <small class="text-danger">
                                {% if form.errors %}
                                {% for field in form %}
                                {% if field.errors %}
                                {% for error in field.errors %}
                                {{ error|escape }}
                                {% endfor %}
                                {% endif %}
                                {% endfor %}

                                {% if form.non_field_errors%}
                                {% for error in form.non_field_errors %}
                                {{ error|escape }}
                                {% endfor %}
                                {% endif %}
                                {% endif %}
                            </small>
                            <div class="dropdown-divider"></div>

                            <div class="form-group row">
                                <label for="id_contract" class="col-sm-2 col-form-label">Orden de pauta</label>
                                <div class="col-sm-10">
                                    <!-- <select name="category" id="id_category" required class="form-control">
                                        <option value="" selected>---------</option>
                                        
                                    </select> -->
                                    {{ form.contract}}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_name" class="col-sm-2 col-form-label">Nombre del video</label>
                                <div class="col-sm-10 ">
                                    <input type="text" name="name" maxlength="50" class="form-control" required
                                        autocomplete="off" id="id_name" value="{% if obj %} {{obj.name}} {% endif %}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_duration" class="col-sm-2 col-form-label">duracion del video</label>
                                <div class="col-sm-10 ">
                                    <input type="time" name="duration" maxlength="50" class="form-control" required
                                        autocomplete="off" id="id_duration" value="{% if obj %}{{obj.duration_all}}{% endif %}" step="1">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="id_description" class="col-sm-2 col-form-label">Descripcion</label>
                                <div class="col-sm-10">
                                    <input type="" name="description" maxlength="100" class="form-control"
                                        autocomplete="off" id="id_description"
                                        value="{% if obj %} {{obj.description}} {% endif %}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_start_date" class="col-sm-2 col-form-label">Fecha Inicio</label>
                                <div class="col-sm-4 ">
                                    <input type="date" name="start_date" class="form-control" id="id_start_date"
                                        value="{% if obj %}{{obj.start_date|date:'Y-m-d'}}{% endif %}">
                                </div>

                                <label for="id_end_date" class="col-sm-2 col-form-label">Fecha Final</label>
                                <div class="col-sm-4 ">
                                    <input type="date" name="end_date" class="form-control" id="id_end_date"
                                        value="{% if obj %}{{obj.end_date|date:'Y-m-d'}}{% endif %}">
                                </div>
                            </div>
                            <!-- para mostrar video -->
                            <!-- <div class="form-group row ">
                                <div class="embed-responsive embed-responsive-21by9">

                                    <video width="320" height="240" controls class="embed-responsive-item" id="video_rep">
                                        <source type="video/mp4" src="" id="video_local">
                                    </video>
                                </div>
                            </div> -->




                            <!-- <div class="form-group row">
                                <label for="id_img" class="col-sm-2 col-form-label">Imagen</label>
                                <div class="col-sm-10">
                                    <input type="file" name="img" maxlength="300" class="form-control-file"
                                        accept="image/*" id="id_img" value="{% if obj %} {{obj.img}} {% endif %}">
                                </div>
                            </div> -->
                            <!-- <div class="form-group row">
                                <label for="id_video" class="col-sm-2 col-form-label">Video</label>
                                <div class="col-sm-10">
                                    <input type="file" name="video" maxlength="300" class="form-control-file"
                                        accept="video/*" id="id_video" value="{% if obj %} {{obj.video}} {% endif %}">
                                </div>
                            </div> -->
                            <div class="form-group row">
                                <div class="col-sm-2">Estado</div>
                                <div class="col-sm-10">
                                    <div class="form-check">
                                        <input type="checkbox" name="state" class="form-check-input" {% if obj.state == True %}
                                            checked {% endif %} id="id_state">
                                        <label class="form-check-label" for="id_state">
                                            Marcar estado.
                                        </label>
                                    </div>

                                </div>
                            </div>





                            <!-- {{form.as_p}} -->

                            <div class="dropdown-divider"></div>
                            <div class="form-group row text-center">
                                <div class="col-sm-12">
                                    <a href="{% url 'content:videos_list' %}" class="btn btn-danger"><span
                                            class="fa fa-undo"> Cancelar</span></a>
                                    <button type="submit" class="btn btn-success"><span class="fa fa-save"></span>
                                        Guardar</button>
                                </div>
                            </div>
                            <!-- <button type="button" id="sacar_tiempo">sacr</button> -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>

{% endblock %}
{% block js_page %}
<script>
    $(document).ready(function () {
        $('#id_contract').select2({ placeholder: "Seleccione", allowClear: true });

        $('#id_state').prop("checked", true);

    })

    $("#id_video").change(function () {
        var $source = $("#video_local");
        $source[0].src = URL.createObjectURL(this.files[0]);
        $source.parent()[0].load();
        console.log($source.parent()[0].duration);


    });

    $("#sacar_tiempo").click(function () {
        
        console.log($("#video_rep"));


    });

    $('#id_contract').change(function (){
        contract = $("#id_contract option:selected").text();
        aux = contract.split("desde el ")
        name = 'spot ' +aux[0] 
        date_start = aux[1].split(" al ")[0]
        date_end = aux[1].split(" al ")[1]
        // console.log(name);
        // console.log(date_end);

        $("#id_start_date").val(date_start);
        $("#id_end_date").val(date_end);
        $("#id_name").val(name);




    });

</script>

{% endblock %}