app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [

    path('', include(('bases.urls', 'bases'), namespace='bases')),
    # rutas de modulo componentes
    path('component/', include(('component.urls', 'component'), namespace='component')),

    # rutas del modulo ventas
    path('sales/', include(('sales.urls', 'sales'), namespace='sales')),
    # rutas para ocontenidos y videos pautas
    path('content/', include(('content.urls', 'content'), namespace='content')),
    # ruta para los reportes y envio de mails
    path('report/', include(('report.urls', 'report'), namespace='report')),
    # rutas para los reportes que se pueden imprimir
    path('reportprint/', include(('reportprint.urls',
                                  'reportprint'), namespace='reportprint')),

    # rutas para los reportes de emision de cliente y mensual general
    path('reportemision/', include(('reportemision.urls',
                                    'reportemision'), namespace='reportemision')),

    # rutas para rondas de personal en las locaciones
    path('rondas/', include(('rondas.urls', 'rondas'), namespace='rondas')),

    # rutas para mostrar vistas de reportes rapidos como clinetes por locaion spots por clientes
    path('display/', include(('display.urls', 'display'), namespace='display')),

    # rutas para mostrar vistas de reportes rapidos como clinetes por locaion spots por clientes
    path('maintenance/', include(('maintenance.urls', 'maintenance'), namespace='maintenance')),

    # rutas para mostrar todos los contratos y sus locaciones con sus respectivos spots 
    path('allviewcontract/', include(('allviewcontract.urls', 'allviewcontract'), namespace='allviewcontract')),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maintenance/urls.py
from django.urls import path
from .views import maintenance_list, maintenance_new, subproducts_get, electronic_get, maintenance_edit, maintenance_delete


urlpatterns = [
    # vistas para registro de mantenimineto
    path('maintenance/', maintenance_list, name='maintenance_list'),
    path('maintenance/new', maintenance_new, name='maintenance_new'),
    path('maintenance/edit/<int:id>', maintenance_edit, name='maintenance_edit'),
    path('maintenance/delete/<int:id>', maintenance_delete, name='maintenance_delete'),


    path('subproduct_get/<int:id>', subproducts_get, name='subproduct_get'),
    path('electronic_get/<int:id>', electronic_get, name='electronic_get'),


    # path('ronda/view/<int:id>', inplace_view, name='ronda_view'),
    # path('videos/edit/<int:pk>',
    #      VideoEdit.as_view(), name='video_edit'),
    # path('videos/disabled/<int:id>', video_disabled, name='video_disabled'),

]

maintenance/models.py
from django.db import models

from bases.models import ClassModel

from component.models import Product
# Create your models here.
 

class Maintenance(ClassModel):
    
    created_date = models.DateTimeField(null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    sub_product = models.IntegerField(blank=True, null=True)
    electronic = models.IntegerField(blank=True, null=True)
    collaboration = models.CharField(max_length=200, blank=True, null=True)
    work_done = models.TextField(max_length=1000, blank=True, null=True)
    conclusions = models.TextField(max_length=1000, blank=True, null=True)
    
    def __str__(self):
        
        return '{} {}'.format(self.product, self.created_date)

sales/models.py
from django.db import models
from bases.models import ClassModel

from component.models import Product

from datetime import datetime

# modelo para clientes

class Client(ClassModel):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=150, null=True, blank=True)
    img = models.ImageField(upload_to='clients', blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.name)
# ordenes de pautaa
class Contract(ClassModel):
    start_date = models.DateField(auto_now=False, null=True, blank=True)
    end_date = models.DateField(auto_now=False, null=True, blank=True)
    description = models.CharField(max_length=150, null=True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    auspice = models.BooleanField(default=False)

    def __str__(self):
        
        return '{}, {} desde el {} al {}'.format(self.client.name, self.description, self.start_date   ,self.end_date)

    
        

# orden por cada producto

class Order(ClassModel):
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    pass_contract = models.IntegerField(default=0)
    porcentage_contract = models.FloatField(default=0)
    description = models.CharField(max_length=150, null=True, blank=True)
    

    def __str__(self):
        return '{}'.format(self.description)

# url de respaldo 
class Respaldo(ClassModel):
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    month_year = models.CharField(max_length=50, null=False, blank=False)
    year = models.ImageField(null=False, blank=False)
    url = models.CharField(max_length=500, null=False, blank=False)
    description = models.CharField(max_length=150, null=True, blank=True)

maintenance/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.shortcuts import render

from django.views import generic
from django.urls import reverse_lazy

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin


# importacion pra la vista basada en funciones
from django.contrib.auth.decorators import login_required, permission_required

from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.http import HttpResponse
import json

from bases.views import SinPrivilegios

from component.models import Product, Subproduct, Electronic
from .models import Maintenance

import math

from datetime import datetime


@login_required(login_url='/login/')
@permission_required('maintenance.view_maintenance', login_url='bases:sin_privilegios')
def maintenance_list(request):
    template_name = 'maintenance/maintenance_list.html'
    contexto = {}
    obj = Maintenance.objects.filter(state=True).all()

    if not obj:
        contexto = {'obj': ''}

    if request.method == 'GET':
        contexto = {'obj': obj}

    return render(request, template_name, contexto)


@login_required(login_url='/login/')
@permission_required('maintenance.view_maintenance', login_url='bases:sin_privilegios')
def maintenance_new(request):
    template_name = 'maintenance/maintenance_form.html'
    contexto = {}
    obj = Maintenance.objects.filter(state=True).all()
    products = Product.objects.filter(state=True).all()

    if not obj:
        contexto = {'obj': ''}

    if request.method == 'GET':
        contexto = {'obj': obj, 'products': products}

    if request.method == 'POST':
        # print(request.POST)
        created_date_str = request.POST.get('created_date')
        id_product = request.POST.get('product')
        subproduct = request.POST.get('subproduct')
        electronic = request.POST.get('electronic')
        collaboration = request.POST.get('collaboration')
        work_done = request.POST.get('work_done')
        conclusions = request.POST.get('conclusions')

        # datetime_str = '2016-10-03T19:00:00.999Z'

        created_date = datetime.strptime(created_date_str, "%d/%m/%Y %H:%M:%S")

        # created_date = created_date_str
        print(type(created_date))
        print(created_date)
        if subproduct == '':
            subproduct = 0
        if electronic == '':
            electronic = 0

        product = Product.objects.get(pk=id_product)

        maintenance = Maintenance
        maintenance = Maintenance(
            created_date=created_date,
            product=product,
            sub_product=subproduct,
            electronic=electronic,
            collaboration=collaboration,
            work_done=work_done,
            conclusions=conclusions,
            state=True,
            user_created=request.user

        )
        maintenance.save()

        return redirect("maintenance:maintenance_list")

    return render(request, template_name, contexto)


@login_required(login_url='/login/')
@permission_required('maintenance.view_maintenance', login_url='bases:sin_privilegios')
def maintenance_edit(request, id):
    template_name = 'maintenance/maintenance_edit.html'
    contexto = {}
    obj = Maintenance.objects.get(pk=id)

    if not obj:
        contexto = {'obj': ''}

    if request.method == 'GET':
        product = obj.product
        # print(obj.sub_product)
        # print(obj.electronic)

        subproduct = Subproduct.objects.filter(id=obj.sub_product).first()
        electronic = Electronic.objects.filter(id=obj.electronic).first()
        contexto = {'obj': obj, 'product': product,
            'subproduct': subproduct, 'electronic': electronic}

    if request.method == 'POST':
        # print(request.POST)

        collaboration = request.POST.get('collaboration')
        work_done = request.POST.get('work_done')
        conclusions = request.POST.get('conclusions')

        obj.collaboration = collaboration
        obj.work_done = work_done
        obj.conclusions = conclusions
        obj.state = True
        obj.user_updated = request.user.id

        
        obj.save()

        return redirect("maintenance:maintenance_list")

    return render(request, template_name, contexto)


def subproducts_get(request, id):
    # usado por ajax
    contexto={}
    if request.method == 'GET':
        subproduct=Subproduct.objects.filter(product = id).all()



        subproduct_json=[]
        for item in subproduct:
            objeto_order={}
            objeto_order["id"]=item.id
            objeto_order["name"]=item.name
            objeto_order["place"]=item.place
            objeto_order["measure"]=item.measure
            subproduct_json.append(objeto_order)

        # TODO: ver la forma de enviar el nombre de la inagen

        contexto={'obj': 'OK', 'subproduct': subproduct_json}
        return HttpResponse(json.dumps(contexto), content_type = json)

def electronic_get(request, id):
    # usado por ajax
    contexto={}
    if request.method == 'GET':
        electronic=Electronic.objects.filter(sub_product = id).all()



        electronic_json=[]
        for item in electronic:
            objeto={}
            objeto["id"]=item.id
            objeto["name"]=item.name
            objeto["serie"]=item.serie
            objeto["measure"]=item.measure
            electronic_json.append(objeto)

        # TODO: ver la forma de enviar el nombre de la inagen

        contexto={'obj': 'OK', 'electronic': electronic_json}
        return HttpResponse(json.dumps(contexto), content_type = json)

def maintenance_delete(request, id):
    template_name = 'maintenance/maintenance_delete.html'
    contexto = {}
    obj = Maintenance.objects.get(pk=id)

    if not obj:
        return HttpResponse('no existe' + str(id))

    if request.method == 'GET':
        contexto = {'obj': obj}

    if request.method == 'POST':
        # cat.state = False
        obj.delete()
        # return redirect("maintenance:maintenance_list")
        contexto = {'obj': 'OK'}
        return HttpResponse('OK')

    return render(request, template_name, contexto)

maintenance/templates/maintenance/maintenance_edit.html
{% extends 'base/base.html' %}

{% block page_content %}

<form method="POST" class="form-group" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="col-xl-12 col-md-12 mb-12">



        <div class="card border-left-primary shadow h-100 py-2">


            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold  text-uppercase mb-1 text-center">
                            <h4>formulario de
                                mantenimiento  RPK-000{{obj.id}}  </h4>
                        </div>
                        <small class="text-danger">
                            {% if form.errors %}
                            {% for field in form %}
                            {% if field.errors %}
                            {% for error in field.errors %}
                            {{ error|escape }}
                            {% endfor %}
                            {% endif %}
                            {% endfor %}

                            {% if form.non_field_errors%}
                            {% for error in form.non_field_errors %}
                            {{ error|escape }}
                            {% endfor %}
                            {% endif %}
                            {% endif %}
                        </small>
                        <div class="dropdown-divider"></div>
                       
                        <div class="form-group row ">
                            <label for="id_name" class="col-sm-2 col-form-label">Nombre</label>
                            <div class="col-sm-5 ">
                                <input type="text" name="name" maxlength="50" class="form-control" required readonly
                                    autocomplete="off" id="id_name"
                                    value=" {{ obj.user_created.first_name}} {{ obj.user.last_name}} ">
                            </div>
                            <label for="id_created_date" class="col-sm-2 col-form-label">Fecha</label>
                            <div class="col-sm-3 ">
                                <input type="datetime" name="created_date" class="form-control" id="id_created_date"
                                    value="{{obj.created_date}}" readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="id_product" class="col-sm-2 col-form-label">Producto</label>
                            <div class="col-sm-10">

                                <input type="text" name="" class="form-control" autocomplete="off" id=""
                                    value="{{product}}" readonly>


                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_subproduct" class="col-sm-2 col-form-label">Sub producto</label>
                            <div class="col-sm-10">
                                <input type="text" name="" class="form-control" autocomplete="off" id=""
                                    value="{{subproduct.name}} {{subproduct.place}} {{subproduct.measure}}" readonly>


                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_electronic" class="col-sm-2 col-form-label">Electronico</label>
                            <div class="col-sm-10">
                                <input type="text" name="" class="form-control" autocomplete="off" id=""
                                    value="{{electronic.name}} serie: {{electronic.serie}} {{electronic.measure}} {{electronic.info}}"
                                    readonly>


                            </div>
                        </div>
                        <div class="form-group row ">
                            <label for="id_collaboration" class="col-sm-2 col-form-label">Colaboradores</label>
                            <div class="col-sm-10 ">
                                <input type="text" name="collaboration" maxlength="50" class="form-control"
                                    autocomplete="off" id="id_collaboration" value="{{obj.collaboration}}">
                            </div>

                        </div>

                        <div class="form-group row ">
                            <div class="col-sm-2"></div>

                            <div class="col-sm-10">

                                <label class="" for="id_work_done">
                                    Trabajo realizado
                                </label>
                                <textarea class="form-control" name="work_done" id="id_work_done"
                                    rows="6">{{obj.work_done}}</textarea>


                            </div>
                        </div>
                        <div class="form-group row ">
                            <div class="col-sm-2"></div>

                            <div class="col-sm-10">

                                <label class="" for="id_conclusions">
                                    Conclusion
                                </label>
                                <textarea class="form-control" name="conclusions" id="id_conclusions"
                                    rows="3">{{obj.conclusions}}</textarea>


                            </div>
                        </div>

                        <div class="dropdown-divider"></div>
                        <div class="form-group row text-center">
                            <div class="col-sm-10">
                                <a href="{% url 'maintenance:maintenance_list' %}" class="btn btn-danger"><span
                                        class="fa fa-undo"> Cancelar</span></a>
                                <button type="submit" class="btn btn-success"><span class="fa fa-save"></span>
                                    Guardar</button>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}
{% block js_page %}
<script>
    

</script>


{% endblock %}

maintenance/templates/maintenance/maintenance_form.html
{% extends 'base/base.html' %}

{% block page_content %}

<form method="POST" class="form-group" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="col-xl-12 col-md-12 mb-12">



        <div class="card border-left-primary shadow h-100 py-2">


            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold  text-uppercase mb-1 text-center">
                            <h4>Registro: formulario de
                                mantenimiento</h4>
                        </div>
                        <small class="text-danger">
                            {% if form.errors %}
                            {% for field in form %}
                            {% if field.errors %}
                            {% for error in field.errors %}
                            {{ error|escape }}
                            {% endfor %}
                            {% endif %}
                            {% endfor %}

                            {% if form.non_field_errors%}
                            {% for error in form.non_field_errors %}
                            {{ error|escape }}
                            {% endfor %}
                            {% endif %}
                            {% endif %}
                        </small>
                        <div class="dropdown-divider"></div>
                        <!--  -->
                        <div class="form-group row ">
                            <label for="id_name" class="col-sm-2 col-form-label">Nombre</label>
                            <div class="col-sm-5 ">
                                <input type="text" name="name" maxlength="50" class="form-control" required readonly
                                    autocomplete="off" id="id_name"
                                    value=" {{ user.first_name}} {{ user.last_name}} ">
                            </div>
                            <label for="id_created_date" class="col-sm-2 col-form-label">Fecha</label>
                            <div class="col-sm-3 ">
                                <input type="datetime" name="created_date" class="form-control" id="id_created_date"
                                    value="" readonly>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="id_product" class="col-sm-2 col-form-label">Producto</label>
                            <div class="col-sm-10">
                                <select name="product" id="id_product" required class="form-control">
                                    <option value="" selected>Seleccione...</option>
                                    {% for prod in products %}
                                    <option value="{{prod.id}}">{{prod}}</option>
                                    {% endfor %}

                                </select>

                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_subproduct" class="col-sm-2 col-form-label">Sub producto</label>
                            <div class="col-sm-10">
                                <select name="subproduct" id="id_subproduct" class="form-control">
                                    <option value="" selected>Seleccione...</option>

                                </select>

                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_electronic" class="col-sm-2 col-form-label">Electronico</label>
                            <div class="col-sm-10">
                                <select name="electronic" id="id_electronic" class="form-control">
                                    <option value="" selected>Seleccione...</option>

                                </select>

                            </div>
                        </div>
                        <div class="form-group row ">
                            <label for="id_collaboration" class="col-sm-2 col-form-label">Colaboradores</label>
                            <div class="col-sm-10 ">
                                <input type="text" name="collaboration" maxlength="50" class="form-control"
                                    autocomplete="off" id="id_collaboration"
                                    value="  ">
                            </div>
                           
                        </div>

                        <div class="form-group row ">
                            <div class="col-sm-2"></div>

                            <div class="col-sm-10">

                                <label class="" for="id_work_done">
                                    Trabajo realizado
                                </label>
                                <textarea class="form-control" name="work_done" id="id_work_done" rows="6"></textarea>


                            </div>
                        </div>
                        <div class="form-group row ">
                            <div class="col-sm-2"></div>

                            <div class="col-sm-10">

                                <label class="" for="id_conclusions">
                                    Conclusion
                                </label>
                                <textarea class="form-control" name="conclusions" id="id_conclusions"
                                    rows="3"></textarea>


                            </div>
                        </div>

                        <div class="dropdown-divider"></div>
                        <div class="form-group row text-center">
                            <div class="col-sm-10">
                                <a href="{% url 'maintenance:maintenance_list' %}" class="btn btn-danger"><span
                                        class="fa fa-undo"> Cancelar</span></a>
                                <button type="submit" class="btn btn-success"><span class="fa fa-save"></span>
                                    Guardar</button>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}
{% block js_page %}
<script>
    $(document).ready(function () {
        $('#id_product').select2({ placeholder: "Seleccione", allowClear: true });
        $('#id_subproduct').select2({ placeholder: "Seleccione", allowClear: true });
        $('#id_electronic').select2({ placeholder: "Seleccione", allowClear: true });

        var hoy = new Date();
        var fecha = hoy.getDate() + '/' + (hoy.getMonth() + 1) + '/' + hoy.getFullYear();
        // var fecha =  hoy.getFullYear() + '/' + (hoy.getMonth() + 1) + '/' + hoy.getDate()
        var hora = hoy.getHours() + ':' + hoy.getMinutes() + ':' + hoy.getSeconds();
        var datetime_insitu = fecha + ' ' + hora;
        $('#id_created_date').val(datetime_insitu);
    })


    $("#id_product").change(function () {
        product_id = $("#id_product").val();
        product_name = $("#id_product option:selected").text();


        console.log(product_id);
        if (product_id == '') {

            mensaje("escoger un producto con valor", "red");
            return;
        }
        $("#id_subproduct").empty();
        var id_product = product_id;
        var token = '{{csrf_token}}';
        $.ajax({
            headers: { "X-CSRFToken": token },
            type: "GET",
            url: "/maintenance/subproduct_get/" + id_product,

            success: function (response) {
                aux = response

                for (let index = 0; index < aux.subproduct.length; index++) {

                    $("#id_subproduct").append('<option value="' + aux.subproduct[index].id + '">' + aux.subproduct[index].name + '</option>');
                    console.log(aux.subproduct[index].id)
                }

            },
            error: function (jqXHR, textStatus, errorThrow) {
                console.log(textStatus, errorThrow);
                mensaje(errorThrow, 'red');
                cerrar_modal();
            }
        });
    });


    $("#id_subproduct").change(function () {
        id = $("#id_subproduct").val();

        if (id == '') {

            mensaje("escoger un sub producto con valor", "red");
            return;
        }
        $("#id_electronic").empty();
        var token = '{{csrf_token}}';
        $.ajax({
            headers: { "X-CSRFToken": token },
            type: "GET",
            url: "/maintenance/electronic_get/" + id,

            success: function (response) {
                aux = response

                for (let index = 0; index < aux.electronic.length; index++) {

                    $("#id_electronic").append('<option value="' + aux.electronic[index].id + '">' + aux.electronic[index].name + '</option>');
                    console.log(aux.electronic[index].id)
                }

            },
            error: function (jqXHR, textStatus, errorThrow) {
                console.log(textStatus, errorThrow);
                mensaje(errorThrow, 'red');
                cerrar_modal();
            }
        });

    });

</script>


{% endblock %}

maintenance/templates/maintenance/maintenance_list.html
{% extends 'base/base.html' %}

{% block page_content %}

<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de mantenimientos</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>

                <a class="dropdown-item" href="{% url 'maintenance:maintenance_new' %}"><i class="far fa-calendar-plus"></i>
                    Nuevo</a>

            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hay registro de mantenimientos</div>

        {% else %}
        <div class="table-responsive">

            <table class="table table-striped table-hover table-bordered table-sm" data-page-length='25'>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Usuario</th>
                        <th>Fecha</th>
                        <th>Producto</th>
                        <th>Users</th>
                        <th>Concluciones</th>

                        <!-- <th>UC</th> -->
                        <!-- <th>UM</th> -->
                        <th class="all">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.user_created.first_name }} {{item.user_created.last_name}}</td>
                        <td>{{ item.created_date }}</td>
                        <td>{{item.product}} </td>
                        <td>{{ item.collaboration }}</td>
                       
                        <td>{{ item.conclusions }}</td>
                       
                        <!-- <td>{{ item.user_created}}</td> -->
                        <!-- <td>{{ item.user_updated}}</td> -->
                        <!-- para fecha formateada |date: "d/m/Y H:i:s" -->

                        <td>
                            {% if perms.maintenance.change_maintenance %}
                            <a href="{% url 'maintenance:maintenance_edit' item.id %}"
                                class="btn btn-sm btn-outline-warning btn-circle" role="button"><i
                                    class="far fa-edit"></i></a>
                            {% endif %}
                            {% if perms.maintenance.delete_maintenance %}
                            <button class="btn btn-sm btn-outline-danger btn-circle"
                                onclick="return abrir_modal('{% url 'maintenance:maintenance_delete' item.id %}')"><i
                                    class="far fa-trash-alt"></i></button>
                            {% endif %}

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}


{% block js_page %}
<script>
    $(document).ready(function () {
        $('.table').DataTable({
            show: 20
        });
    })
</script>


{% endblock %}