app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [

    path('', include(('bases.urls', 'bases'), namespace='bases')),
    # rutas de modulo componentes
    path('component/', include(('component.urls', 'component'), namespace='component')),

    # rutas del modulo ventas
    path('sales/', include(('sales.urls', 'sales'), namespace='sales')),
    # rutas para ocontenidos y videos pautas
    path('content/', include(('content.urls', 'content'), namespace='content')),
    # ruta para los reportes y envio de mails
    path('report/', include(('report.urls', 'report'), namespace='report')),
    # rutas para los reportes que se pueden imprimir
    path('reportprint/', include(('reportprint.urls',
                                  'reportprint'), namespace='reportprint')),

    # rutas para los reportes de emision de cliente y mensual general
    path('reportemision/', include(('reportemision.urls',
                                    'reportemision'), namespace='reportemision')),

    # rutas para rondas de personal en las locaciones
    path('rondas/', include(('rondas.urls', 'rondas'), namespace='rondas')),

    # rutas para mostrar vistas de reportes rapidos como clinetes por locaion spots por clientes
    path('display/', include(('display.urls', 'display'), namespace='display')),

    # rutas para mostrar vistas de reportes rapidos como clinetes por locaion spots por clientes
    path('maintenance/', include(('maintenance.urls', 'maintenance'), namespace='maintenance')),

    # rutas para mostrar todos los contratos y sus locaciones con sus respectivos spots 
    path('allviewcontract/', include(('allviewcontract.urls', 'allviewcontract'), namespace='allviewcontract')),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reportemision/urls.py
from django.urls import path
from .views import  report_client, report_client_all, order_report_list, order_report_print, \
    report_client_generate, report_generate_save, report_client_view, \
    report_client_xls, report_client_day_view, report_day_delete

urlpatterns = [
    # vistas para reportes
    path('report_client/',report_client, name='report_client'),

    path('report_client/<int:id>',report_client_all, name='report_client_all'),

    path('order_report/<int:id>', order_report_list, name='order_report_list'),


    path('order_report_print/<int:id>', order_report_print, name='order_report_print'),

    # path('report_playlist_xls/<int:id>',report_playlist_xls, name='report_playlist_xls'),
    # ruta
    path('report_client_generate/<int:id>',report_client_generate, name='report_client_generate'),
    path('report_client_view/<int:id>',report_client_view, name='report_client_view'),
    
    path('report_client_day/view/<int:order_id>/<int:video_id>/<int:playlist_id>', report_client_day_view, name='report_client_day_view'),
    
    
    # ajax
    path('report_day/delete/<int:id>', report_day_delete, name='report_day_delete'),


    path('report_client_xls/<int:id>/<slug:month>/<int:order_id>',report_client_xls, name='report_client_xls'),
    path('report_generate_save/',report_generate_save, name='report_generate_save'),


    # rutas de proyecciones 
]

reportprint/urls.py
from django.urls import path
from .views import  report_contract, report_playlist, report_playlist_xls

urlpatterns = [
    # vistas para ventas
    path('report_contract/<int:id>',report_contract, name='report_contract'),

    path('report_platlist/<int:id>',report_playlist, name='report_playlist'),

    path('report_playlist_xls/<int:id>',report_playlist_xls, name='report_playlist_xls'),

    
    
]

sales/urls.py
from django.urls import path
from .views import  ContractList, ClientView, ClientNew, ClientEdit, client_delete, \
    ContractList,contract_view,  contract_create, contract_edit, contract_delete, contract_list, contract_disabled, \
    order_delete, order_new, order_update, order_view_id,  \
    url_admin, url_new, url_id, url_delete

urlpatterns = [
    # vistas para ventas
    path('client/',ClientView.as_view(), name='client_list'),
    path('client/new',ClientNew.as_view(), name='client_new'),
    path('client/edit/<int:pk>',ClientEdit.as_view(), name='client_edit'),
    path('client/delete/<int:id>',client_delete, name='client_delete'),

    path('contract/',ContractList.as_view(), name='contract_list'),
    path('contract/view/<int:id>',contract_view, name='contract_view'),
    path('contract/new/',contract_create, name='contract_new'),
    path('contract/edit/<int:id>',contract_edit, name='contract_edit'),
    path('contract/delete/<int:id>',contract_delete, name='contract_delete'),

    path('contract/disabled/<int:id>',contract_disabled, name='contract_disabled'),

    path('contract/list/',contract_list, name='contract_list_ajax'),



    path('order/new',order_new, name='order_new'),
    path('order/delete/<int:id>',order_delete, name='order_delete'),
    path('order/update/<int:id>',order_update, name='order_update'),
    path('order/edit/<int:id>',order_view_id, name='order_edit'),

    # urls para crear url ubicaciones de google drive en la cuenta de repositorio 

    path('url_admin/<int:id>',url_admin, name='url_admin'),
    # ajax
    path('url_new/<int:id>',url_new, name='url_new'),
    path('url_id/view/<int:id>',url_id, name='url_id'),
    path('url_delete/<int:id>',url_delete, name='url_delete'),


    
]

reportemision/models.py
from django.db import models

from bases.models import ClassModel
from sales.models import Contract, Order
from content.models import Video, Playlist
from component.models import Product
# Create your models here.
 

class Document(ClassModel):

    start_date = models.DateField(null=False, blank=False)
    end_date = models.DateField(null=False, blank=False)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    # duration_pauta = models.IntegerField(null=False, blank=False)
    repeat_pauta_day = models.FloatField(null=False, blank=False)
    repeat_in_pauta = models.IntegerField(null=False, blank=False)
    # second_total_pauta = models.IntegerField(null=False, blank=False)
    second_total_day = models.IntegerField(null=False, blank=False)
    time_contract = models.IntegerField(null=False, blank=False)
    time_bonification = models.IntegerField(null=False, blank=False)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)

class Report_day(ClassModel):
    date_now = models.DateField(null=False, blank=False)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)

reportemision/views.py
from django.shortcuts import render, redirect

from django.views import generic
from django.urls import reverse_lazy

from django.contrib import messages

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
import json
import datetime

from datetime import timedelta
import calendar

from openpyxl import Workbook
import openpyxl
import locale 

# from django.utils import simplejson

# from .models import Client, Contract, Order


# from .forms import ClientForm, ContractForm

from sales.models import Contract, Order
from .models import Document, Report_day
from content.models import Video
from content.models import Playlist, Playlist_client_detail, Playlist_spot_detail, Playlist_document


def report_client(request):
    template_name = 'reportemision/contract_list.html'
    contexto = {}
    contract = Contract.objects.filter(state=True).all()

    # today = datetime.datetime.now()
    # order = Order.objects.filter(contract=id)
    if not contract:
        return HttpResponse('el registro con id: ' + str(id) + ' no existe!!!')

    if request.method == 'GET':

        contexto = {'obj': contract}

    return render(request, template_name, contexto)


def order_report_list(request, id):
    # id => contract_id
    template_name = 'reportemision/order_report_list.html'
    contexto = {}

    document = Document.objects.filter(contract=id).all()

    contexto = {'obj': document}
    return render(request, template_name, contexto)


def order_report_print(request, id):
    template_name = 'reportemision/order_report_print.html'
    contexto = {}

    document = Document.objects.get(pk=id)

    playlist_spot = Playlist_spot_detail.objects.filter(
        order_id=document.order.id, playlist_id=document.playlist_id).all()
    videos = []
    time_in_pauta_total = 0
    repeat_in_pauta = 0
    videos_id = []
    for item in playlist_spot:
        objeto = {}
        video = Video.objects.get(pk=item.video_id)
        videos_id.append(video.id)
        objeto['name_video'] = video.name
        objeto['duration'] = video.duration_all
        objeto['duration_seconds'] = video.duration_seconds
        objeto['repeat_in_pauta'] = item.repeat_count
        objeto['time_in_pauta'] = item.time_total
        time_in_pauta_total = time_in_pauta_total + int(item.time_total)
        repeat_in_pauta = repeat_in_pauta + int(item.repeat_count)
        
        videos.append(objeto)

    playlist = Playlist_document.objects.filter(
        playlist_id=document.playlist_id).all().order_by('order_list')
    playlist_client = []
    for item in playlist:
        objeto = {}
        objeto['orden_list'] = item.order_list
        if (not item.video.id in videos_id):
            objeto['name_video'] = 'Otro cliente'
            objeto['color'] = 0
        else:
            objeto['name_video'] = item.video.name
            objeto['color'] = 1
        objeto['duration'] = item.video.duration_all()
        playlist_client.append(objeto)
#
    # for item in playlist_client:
        # print(item)
    pass_day = int(repeat_in_pauta) * int(document.repeat_pauta_day)
    contexto = {'obj': document, 'videos': videos, 'time': time_in_pauta_total,
                'time2': repeat_in_pauta, 'playlist': playlist_client, 'pass_day':pass_day}

    return render(request, template_name, contexto)
# ============################################################


def report_client_all(request, id):
    template_name = 'reportemision/contract_list.html'
    contexto = {}

    contract = Contract.objects.get(pk=id)
    order = Order.objects.filter(contract=id)
    color = 1
    report = []
    # print(contract)
    for i in order:
        order_id = i.id
        # print(i.id)
        playlist_client_detail = Playlist_client_detail.objects.filter(
            order=order_id).order_by('playlist__create_date')
        if playlist_client_detail:
            for j in playlist_client_detail:

                # print(j.order.id)
                playlist_spot_detail = Playlist_spot_detail.objects.filter(
                    playlist=j.playlist.id, order=order_id)
                for k in playlist_spot_detail:
                    # print(k.video.name)
                    # se extrae informacion por videos de todos los contratos
                    item = {}
                    item["id"] = str(order_id) + str(k.video.id) + \
                        str(j.playlist.product.id)
                    item["contract_id"] = contract.id 
                    item["order_id"] = order_id
                    item["video_id"] = k.video.id
                    item["client"] = contract.client.name
                    item["start_date"] = contract.start_date
                    item["end_date"] = contract.end_date
                    item["playlist_id"] = j.playlist.id
                    item["location"] = j.playlist.product
                    item["create_date"] = j.playlist.create_date
                    item["video_name"] = k.video.name
                    item["video_duration"] = k.video.duration_all()
                    item["repeticiones"] = k.repeat_count
                    item["pauta_loop"] = j.pauta_loop
                    item["second_total"] = j.second_total
                    item["time_contract"] = j.time_contract
                    item["time_bonification"] = j.time_bonification
                    item["color"] = color
                    item["state"] = 1
                    item["proyection"] = k.playlist.proyection
                    # print(j.playlist.create_date)
                    report.append(item)
                if color == 1:
                    color = 0
                else:
                    color = 1

        else:
            # encaso de no existir informacion de los videos se toma todo en vacio
            item = {}
            item["id"] = str(order_id) + str(0) + str(i.product.id)
            item["contract_id"] = contract.id
            item["order_id"] = order_id
            item["video_id"] = 0
            item["client"] = contract.client.name
            item["start_date"] = contract.start_date
            item["end_date"] = contract.end_date
            item["playlist_id"] = 0
            item["state"] = 0
            item["location"] = i.product
            item["create_date"] = datetime.datetime.strptime(
                '0001-01-01', "%Y-%m-%d").date()
            item["video_name"] = 'sin registro de playlist'
            item["video_duration"] = 0
            item["repeticiones"] = 0
            item["pauta_loop"] = 0
            item["second_total"] = 0
            item["time_contract"] = 0
            item["time_bonification"] = 0
            item["color"] = 3
            item["proyection"] = False
            report.append(item)

        # report_2 = report_resume(report)
        report_2 = report

    if request.method == 'GET':

        # for m in report:
        # print(m)

        template_name = 'reportemision/contract_date.html'
        contexto = {'report': report, 'contract': contract,
                    'order': order, 'report2': report_2}

        return render(request, template_name, contexto)

    if request.method == 'POST':

        bandera = request.POST.get('bandera')

        start_date_n = request.POST.get('start_date')
        end_date_n = request.POST.get('end_date')

        start_date_n = datetime.datetime.strptime(
            start_date_n, "%Y-%m-%d").date()
        end_date_n = datetime.datetime.strptime(end_date_n, "%Y-%m-%d").date()

        id_report = request.POST.getlist('id_report')
        print(id_report)

        if bandera == '1':
            aux_order = []
            print(bandera)
            for item in report_2:
                if item['id'] in id_report:
                    print(item['id'])
                    if (not item['order_id'] in aux_order):
                        aux_order.append(item['order_id'])
                        order_id = Order.objects.get(pk=item['order_id'])
                        contract_id = Contract.objects.get(pk=item['contract_id'])

                        if not item['playlist_id'] == 0:
                            playlist_id = Playlist.objects.get(
                                pk=item['playlist_id'])
                            document = Document(
                                start_date=start_date_n,
                                end_date=end_date_n,
                                contract=contract_id,
                                order=order_id,
                                repeat_pauta_day=item['pauta_loop'],
                                repeat_in_pauta=item['repeticiones'],

                                second_total_day=item['second_total'],
                                time_contract=item['time_contract'],
                                time_bonification=item['time_bonification'],
                                playlist=playlist_id,
                                user_created=request.user

                            )
                            document.save()
                        contract = Contract.objects.filter(state=True).all()

            template_name = 'reportemision/contract_list.html'

            contexto = {'obj': contract}
        # else:
        #     # diferencia = end_date_n - start_date_n
        #     # diferencia = diferencia.days + 1
        #     # print(diferencia)

        #     report_date = []
        #     # prueba para determinar fechas de inicio y final por cada lista creada
        #     randos_de_fechas = []
        #     aux = []
        #     aux_report = []
        #     for item in report:
        #         aux_report = report
        #         if not(item["id"] in aux):

        #             aux.append(item["id"])
        #             report_id = item["id"]
        #             randos_de_fechas = determinar_fechas(
        #                 aux_report, report_id, start_date_n, end_date_n)

reportemision/templates/reportemision/contract_date_view.html
{% extends 'base/base.html' %}

{% block page_content %}

<form method="POST" class="form-group" enctype="multipart/form-data" id="formulario">
    {% csrf_token %}

    <div class="col-xl-12 col-md-12 mb-12" id="seleccion">
        <div class="card border-left-primary shadow h-100 py-2">

            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Confirmar fechas de reporte.
                        </div>
                        <div class="dropdown-divider"></div>
                        <div>Cliente: <strong>{{contract.client.name}}</strong> </div>
                        <div>Descripción: <strong>{{contract.description}}</strong> </div>
                        <div>Auspicio: <strong>{{contract.auspice|yesno:'Si,No'}}</strong> </div>

                        <div class="form-group row">
                            <!-- <div class="form-control col-6"> -->
                            <label for="id_start_date" class="col-sm-2 col-form-label">Fecha de inicio</label>
                            <div class="col-sm-4 ">
                                <input type="date" name="start_date" class="form-control" id="id_start_date"
                                    value="{{contract.start_date|date:'Y-m-d'}}" required readonly>
                                {% if contract.start_date|date:'Y-m-d' == '1-01-01' or contract.start_date == None %}
                                <h5 class="m-1">Sin fecha</h5>
                                {% endif%}

                            </div>
                            <!-- </div> -->
                            <!-- <div class="form-control col-6 "> -->
                            <label for="id_end_date" class="col-sm-2 col-form-label">Fecha final</label>
                            <div class="col-sm-4 ">
                                <input type="date" name="end_date" class="form-control" id="id_end_date"
                                    value="{{contract.end_date|date:'Y-m-d'}}" required readonly>
                                {% if contract.end_date|date:'Y-m-d' == '1-01-01' or contract.end_date == None %}
                                <h5 class="m-1">Sin fecha</h5>
                                {% endif%}
                            </div>
                            <!-- </div> -->
                        </div>
                        <div> <strong>LOCACIONES CONTRATADAS</strong> </div>
                        <ul class="list-unstyled">
                            <ul>
                                {% for item in order %}
                                <li class="m-2">{{item.product}}</li>
                               
                                
                                
                                <div class="card-columns">
                                    
                                    {% for item2 in obj %}
                                    {% if item.id == item2.order.id%}
                                    <a  href="{% url 'reportemision:report_client_xls' contract.id item2.month_report item.id %}">

                                        <div class="card border-info ">

                                            <div class="card-body text-info text-center">
                                                <h5 class="card-title">{{item2.month_report}}</h5>
                                               
                                            </div>
                                        </div>
                                    </a>
                                   {% endif %}
                                    {% endfor %}
                                </div>

                                {% endfor %}
                            </ul>
                        </ul>




                     


                        <div class="form-row text-center ">

                            <div class="col-sm-10">
                                <a href="{% url 'reportemision:report_client' %}" class="btn btn-danger"><span
                                        class="fa fa-undo"> Cancelar</span></a>
                                <button type="submit" class="btn btn-success" id="btn_guardar"><span
                                        class="fa fa-save"></span>
                                    Guardar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

{% endblock %}

{% block js_page %}
<script>


    // funcion que envia la parte de este spot en la base de datos 
    function send_month(contract_id, month, order_id) {
        console.log(contract_id)
        console.log(month)
        console.log(order_id)

        var token = '{{csrf_token}}';
        var data = { 'month_report': month, 'contract': contract_id, 'order':order_id };

        $.ajax({
            headers: { "X-CSRFToken": token },
            type: "POST",
            url: "/reportemision/report_client_xls/",
            data: data,
            // processData: false,
            // contentType: false,
            success: function (data) {
                // aux = response;
                // console.log(aux)
                var response = JSON.parse(data); 
                window.location = '/Report/Download?fileGuid=' + response.FileGuid + '&filename=' + response.FileName;
                // for (i = 0; i < aux.order.length; i++) {
                //     var check = '<div class="col-12" id="content_product"><div class="form-check">' +
                //         '<input class="form-check-input" type="checkbox" name="clientes_spots"  value="' + aux.order[i].id + '-' + aux.order[i].video_id + '" checked>' +
                //         '<label class="form-check-label">' + aux.order[i].contract + ', pases: ' + aux.order[i].pass + ', %: ' + aux.order[i].porcentage + ', ' + aux.order[i].video_name + ' , duracion: ' + aux.order[i].video_duration + ' </label></div></div>';
                //     $('#content_product').append(check);
                // }



                // $('#btn_clientes').prop('disabled', true);
                // $('#btn_clientes_antiguos').prop('disabled', true);
                // $('#btn_generar_lista').prop('disabled', false);


            },
            error: function (jqXHR, textStatus, errorThrow) {
                console.log(textStatus, errorThrow);
                mensaje(errorThrow, 'red');
                cerrar_modal();
            }
        });


    }





</script>
{% endblock %}

reportemision/templates/reportemision/contract_list.html
{% extends 'base/base.html' %}

{% block page_content %}

<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de clientes con ordenes de trabajo (para reportes)</h6>
        <!-- <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'sales:contract_new' %}">Nuevo</a>
                <a class="dropdown-item" href="#">Reporte Mensual</a>

                <div class="dropdown-divider"></div>

            </div>
        </div> -->
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hay ordenes de trabajo para generar listas de reproducción</div>

        {% else %}
        <div class="table-responsive">

            <table class="table table-striped table-hover table-bordered table-sm" data-page-length='25'>
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Cliente</th>
                        <th>Desc.</th>
                        <th>F. Inicio</th>
                        <th>F. Final</th>
                        <th>Estado</th>
                        <!-- <th>F. Creacion</th> -->
                        <!-- <th>F. Mod</th> -->
                        <!-- <th>U.C</th> -->
                        <!-- <th>U.M</th> -->
                        <th class="all">Acciones</th>

                    </tr>
                </thead>
                <tbody>
                    {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.client}}</td>
                        <td>{{ item.description}}</td>
                        <td>{{ item.start_date|date:"d/m/Y" }}</td>
                        <td>{{ item.end_date|date:"d/m/Y" }}</td>

                        <td>{{ item.state|yesno:"Activo,Inactivo" }}</td>
                        <!-- <td>{{ item.created_at|date:"d/m/Y"}}</td> -->
                        <!-- <td>{{ item.updated_at|date:"d/m/Y"}}</td> -->
                        <!-- <td>{{ item.user_created}}</td> -->
                        <!-- <td>{{ item.user_updated}}</td> -->
                        <!-- para fecha formateada |date: "d/m/Y H:i:s" -->

                        <td class="text-center">
                            <a target="blank" href="{% url 'reportprint:report_contract' item.id %}"
                                class="btn btn-outline-primary btn-circle"><i class="far fa-eye fa-lg"></i></a>
                            <a href="{% url 'reportemision:report_client_all' item.id %}"
                                class="btn btn-outline-success btn-circle"><i class="fas fa-file-invoice fa-lg"></i></a>
                            <a href="{% url 'reportemision:order_report_list' item.id %}"
                                class="btn btn-outline-primary btn-circle"><i
                                    class=" fas fa-receipt fa-lg"></i></a>


                            <!-- <a href="{% url 'sales:contract_edit' item.id %}"
                                class="btn btn-sm btn-outline-warning btn-circle" role="button"><i
                                    class="far fa-edit"></i></a>
                            <button class="btn btn-sm btn-outline-danger btn-circle"
                                onclick="return abrir_modal('{% url 'sales:contract_delete' item.id %}')"><i
                                    class="far fa-trash-alt"></i></button> -->
                            <div class="btn-group role="group">
                                <button id="btnGroupDrop1" type="button" class="btn  btn-outline-secondary  "
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-ellipsis-v fa-sm fa-fw"></i>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                                    <a class="dropdown-item" href="{% url 'reportemision:report_client_generate' item.id %}">Generar Reporte diario</a>
                                    <a class="dropdown-item" href="{% url 'reportemision:report_client_view' item.id %}">Ver Reportes disponibles</a>

                                </div>
                            </div>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}


{% block js_page %}
<script>
    $(document).ready(function () {
        $('.table').DataTable({

        }

        );

    })
</script>


{% endblock %}

reportemision/templates/reportemision/report_day_list.html
{% extends 'base/base.html' %}

{% block page_content %}

<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary text-center">Listado de videos</h6>
        
    </div>
    <!-- Card Body -->
    <div class="card-body">
       
        {% if not obj %}
        <div class="alert alert-info">No hay registros</div>

        {% else %}
        <div class="table-responsive">

            <table class="table table-striped table-hover table-bordered table-sm">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Video</th>
                        <th>Duración</th>
                        <th>Fecha Registro</th>

                        <th class="all">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in obj %}


                    <tr>
                        <td>{{ item.id }}</td>

                        <td>{{ item.video.name }}</td>
                        <td>{{ item.video.duration_all}}</td>
                        <td>{{ item.date_now|date:"d/m/Y" }}</td>


                        <td>
                            <button class="btn btn-sm btn-outline-danger btn-circle"
                                onclick="return abrir_modal('{% url 'reportemision:report_day_delete' item.id %}')"><i
                                    class="far fa-trash-alt"></i></button>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
        {% endif %}
    </div>
    <!-- <div class="card-footer text-center">
        <a class="btn btn-primary " href="{{request.META.HTTP_REFERER}}">
            <i class="fas fa-undo-alt"></i><span class="m-1"> Volver</span>
        </a>
    </div> -->
</div>

{% endblock %}


{% block js_page %}
<script>
    $(document).ready(function () {
        $('.table').DataTable({
        "paging":   false,
        "ordering": true,
        "info":     true
    });
    })
</script>


{% endblock %}