app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [

    path('', include(('bases.urls', 'bases'), namespace='bases')),
    # rutas de modulo componentes
    path('component/', include(('component.urls', 'component'), namespace='component')),

    # rutas del modulo ventas
    path('sales/', include(('sales.urls', 'sales'), namespace='sales')),
    # rutas para ocontenidos y videos pautas
    path('content/', include(('content.urls', 'content'), namespace='content')),
    # ruta para los reportes y envio de mails
    path('report/', include(('report.urls', 'report'), namespace='report')),
    # rutas para los reportes que se pueden imprimir
    path('reportprint/', include(('reportprint.urls',
                                  'reportprint'), namespace='reportprint')),

    # rutas para los reportes de emision de cliente y mensual general
    path('reportemision/', include(('reportemision.urls',
                                    'reportemision'), namespace='reportemision')),

    # rutas para rondas de personal en las locaciones
    path('rondas/', include(('rondas.urls', 'rondas'), namespace='rondas')),

    # rutas para mostrar vistas de reportes rapidos como clinetes por locaion spots por clientes
    path('display/', include(('display.urls', 'display'), namespace='display')),

    # rutas para mostrar vistas de reportes rapidos como clinetes por locaion spots por clientes
    path('maintenance/', include(('maintenance.urls', 'maintenance'), namespace='maintenance')),

    # rutas para mostrar todos los contratos y sus locaciones con sus respectivos spots 
    path('allviewcontract/', include(('allviewcontract.urls', 'allviewcontract'), namespace='allviewcontract')),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from .views import VideoView, VideoNew, VideoEdit, VideoForm, video_delete, video_disabled, \
    playlist_list, playlist_generator, playlist_order, playlist_new, playlist_view, playlist_delete, \
    playlist_order_2, \
    playlist_generator2, playlist_reorder, playlist_edit_date, playlist_proyection, \
    DriveView, DriveNew, DriveEdit, drive_delete

urlpatterns = [
    # vistas para videos
    path('videos/', VideoView.as_view(), name='videos_list'),
    path('videos/new', VideoNew.as_view(), name='video_new'),

    path('videos/edit/<int:pk>',
         VideoEdit.as_view(), name='video_edit'),
    path('videos/disabled/<int:id>', video_disabled, name='video_disabled'),
    path('videos/delete/<int:id>', video_delete, name='video_delete'),



    # rutas para videos
    path('playlist/', playlist_list, name='playlist_list'),
    path('playlist/generator', playlist_generator, name='playlist_generator'),
    path('playlist/generator/hand', playlist_generator2, name='playlist_generator_hand'),

    path('playlist/contract_list/', playlist_generator, name='playlist_contract_list'),
    path('playlist/delete/<int:id>', playlist_delete, name='playlist_delete'),
    path('playlist/proyection/<int:id>', playlist_proyection, name='playlist_proyection'),



    path('playlist/generator/order/', playlist_order, name='playlist_order'),
    path('playlist/new', playlist_new, name='playlist_new'),

    path('playlist/view/<int:id>', playlist_view, name='playlist_view'),
    # playlist_edit_date manejado por ajax
    path('playlist/edit_date', playlist_edit_date, name='playlist_edit_date'),

    
    path('playlist/generator/order_2/', playlist_order_2, name='playlist_order_2'),

    path('playlist/generator/reorder/', playlist_reorder, name='playlist_reorder'),


    # para adminidtrar las ruts a google /drive
    path('drive/',DriveView.as_view(), name='drive_list'),
    path('drive/new',DriveNew.as_view(), name='drive_new'),
    path('drive/edit/<int:pk>',DriveEdit.as_view(), name='drive_edit'),
    path('drive/delete/<int:id>',drive_delete, name='drive_delete'),

]

rondas/urls.py
from django.urls import path
from .views import RondasView, RondaNew, inplace_view, inplace_delete, \
    routes_view, inplace_view_image
# from .views import VideoView, VideoNew, VideoEdit, VideoForm, video_delete, video_disabled, \
    # playlist_list, playlist_generator, playlist_order, playlist_new, playlist_view, playlist_delete

urlpatterns = [
    # vistas para registro de rondas
    path('rondas/', RondasView.as_view(), name='rondas_list'),
    path('ronda/new', RondaNew.as_view(), name='ronda_new'),
    path('ronda/view/<int:id>', inplace_view, name='ronda_view'),

    # path('videos/edit/<int:pk>',
    #      VideoEdit.as_view(), name='video_edit'),
    # path('videos/disabled/<int:id>', video_disabled, name='video_disabled'),
    path('ronda/delete/<int:id>', inplace_delete, name='ronda_delete'),
    path('ronda/view_image/<int:id>', inplace_view_image, name='ronda_view_image'),

    path('ronda/routes/', routes_view, name='routes_view'),


]

bases/models.py
from django.db import models

from django.contrib.auth.models import User

class ClassModel(models.Model):
    state = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_created = models.ForeignKey(User, on_delete=models.CASCADE)
    user_updated = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract=True

content/models.py
from django.db import models

from bases.models import ClassModel
from sales.models import Contract, Order
from component.models import Product, City
# Create your models here.
 

class Video(ClassModel):
    name = models.CharField(max_length=100)
    duration = models.TimeField()
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    description = models.CharField(max_length=100, null=True, blank=True)
    img = models.ImageField(upload_to='videos', null=True, blank=True)
    video = models.FileField(upload_to='videos', null=True, blank=True)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)

    def __str__(self):
        
        return '{}:{}'.format(self.name, self.duration)

    def duration_all(self):
        duration = str(self.duration)
        return duration

    def duration_seconds(self):
        t = self.duration
        seconds = (t.hour * 60 + t.minute) * 60 + t.second
        
        # print(type(seconds)) 
        return seconds


class Playlist(ClassModel):
    create_date = models.DateField(null=False, blank=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    proyection = models.BooleanField(default=False, null=False, blank=False)
    
    def __str__(self):
        return '{} del {} '.format(self.product, self.create_date)

class Playlist_spot_detail(ClassModel):
    repeat_count = models.IntegerField(null=False, blank=False)
    time_total = models.IntegerField(null=False, blank=False)
    porcentage = models.FloatField(null=False, blank=False)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

class Playlist_client_detail(ClassModel):
    time_total = models.IntegerField(null=False, blank=False)
    pauta_loop = models.FloatField(null=False, blank=False)
    second_total = models.IntegerField(null=False, blank=False)
    time_contract = models.IntegerField(null=False, blank=False)
    time_bonification = models.IntegerField(null=False, blank=False)

    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)


class Playlist_document(ClassModel):
    order_list = models.IntegerField(null=False, blank=False)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)


class Drive_urls(ClassModel):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    info = models.CharField(max_length=20, null=True, blank=True)
    url = models.CharField(max_length=500, null=False, blank=False)
    

rondas/models.py
from django.db import models

from bases.models import ClassModel

from component.models import Product
# Create your models here.
 

class Inplace(ClassModel):
    
    datetime_insitu = models.DateTimeField()
    img = models.ImageField(upload_to='rondas')
    description = models.CharField(max_length=100, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    latitude = models.CharField(max_length=100, null=False, blank=False)
    longitude = models.CharField(max_length=100, null=False, blank=False)

    

    def __str__(self):
        
        return '{}'.format(self.datetime_insitu)

    

sales/models.py
from django.db import models
from bases.models import ClassModel

from component.models import Product

from datetime import datetime

# modelo para clientes

class Client(ClassModel):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=150, null=True, blank=True)
    img = models.ImageField(upload_to='clients', blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.name)
# ordenes de pautaa
class Contract(ClassModel):
    start_date = models.DateField(auto_now=False, null=True, blank=True)
    end_date = models.DateField(auto_now=False, null=True, blank=True)
    description = models.CharField(max_length=150, null=True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    auspice = models.BooleanField(default=False)

    def __str__(self):
        
        return '{}, {} desde el {} al {}'.format(self.client.name, self.description, self.start_date   ,self.end_date)

    
        

# orden por cada producto

class Order(ClassModel):
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    pass_contract = models.IntegerField(default=0)
    porcentage_contract = models.FloatField(default=0)
    description = models.CharField(max_length=150, null=True, blank=True)
    

    def __str__(self):
        return '{}'.format(self.description)

# url de respaldo 
class Respaldo(ClassModel):
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE)
    month_year = models.CharField(max_length=50, null=False, blank=False)
    year = models.ImageField(null=False, blank=False)
    url = models.CharField(max_length=500, null=False, blank=False)
    description = models.CharField(max_length=150, null=True, blank=True)

rondas/forms.py
from django import forms

from .models import Inplace

# formulario para categorias
class InplaceForm(forms.ModelForm):
    class Meta:
        model = Inplace
        fields = ['datetime_insitu','img','latitude','longitude','product']
        
        widget = {'latitude': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class':'form-control'})

rondas/views.py
from django.shortcuts import render

from django.views import generic
from django.urls import reverse_lazy

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin


# importacion pra la vista basada en funciones
from django.contrib.auth.decorators import login_required, permission_required

from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.http import HttpResponse
import json

from .models import Inplace
from .forms import InplaceForm


from bases.views import SinPrivilegios

from django.db.models import Count
from django.contrib.auth.models import User






import math

from datetime import datetime

# vistas para Categorias
# TODO: completar los privilegios de los usuarios para cada vista


class RondasView(SinPrivilegios,
                generic.ListView):
    # este permision_required es nesesario para ver el tema de permisos a nivel de vista
    permission_required = 'rondas.view_inplace'
    model = Inplace
    template_name = 'rondas/rondas_view.html'
    context_object_name = 'obj'


class RondaNew(SuccessMessageMixin, LoginRequiredMixin, generic.CreateView):
    model = Inplace
    template_name = 'rondas/inplace_form.html'
    context_object_name = 'obj'
    form_class = InplaceForm
    success_url = reverse_lazy('rondas:rondas_list')
    login_url = 'bases:login'
    success_message = "Creado satisfactoriamente"

    def form_valid(self, form):
        form.instance.user_created = self.request.user

        return super().form_valid(form)


@login_required(login_url='/login/')
@permission_required('rondas.view_inplace', login_url='bases:sin_privilegios')
def inplace_view(request, id):
    template_name = 'rondas/inplace_view.html'
    contexto = {}
    cat = Inplace.objects.filter(pk=id).first()

    if not cat:
        return HttpResponse('Registro no encontrado' + str(id))

    if request.method == 'GET':
        contexto = {'obj': cat}

    if request.method == 'POST':
        # cat.state = False
        cat.update()
        # mensaje par que la vista lo muestre sin coloca en comentarios pues al momento de los esta haciendo con ajax
        # messages.success(request, 'Se inactivo correctamente')

        contexto = {'obj': 'OK'}
        return HttpResponse('Registro  visto')

    return render(request, template_name, contexto)

@login_required(login_url='/login/')
@permission_required('rondas.delete_inplace', login_url='bases:sin_privilegios')
def inplace_delete(request, id):
    template_name = 'rondas/inplace_delete.html'
    contexto = {}
    cat = Inplace.objects.filter(pk=id).first()

    if not cat:
        return HttpResponse('Registro no encontrado' + str(id))

    if request.method == 'GET':
        contexto = {'obj': cat}

    if request.method == 'POST':
        # cat.state = False
        cat.delete()
        # mensaje par que la vista lo muestre sin coloca en comentarios pues al momento de los esta haciendo con ajax
        # messages.success(request, 'Se inactivo correctamente')

        contexto = {'obj': 'OK'}
        return HttpResponse('Registro  eliminado')

    return render(request, template_name, contexto)

@login_required(login_url='/login/')
@permission_required('rondas.view_inplace', login_url='bases:sin_privilegios')
def inplace_view_image(request, id):
    template_name = 'rondas/inplace_view_image.html'
    contexto = {}
    cat = Inplace.objects.get(pk=id)

    if not cat:
        return HttpResponse('Registro no encontrado' + str(id))

    if request.method == 'GET':
        
        contexto = {'obj': cat}


    return render(request, template_name, contexto)


@login_required(login_url='/login/')
@permission_required('rondas.view_inplace', login_url='bases:sin_privilegios')
def routes_view(request):
    template_name = 'rondas/routes_view.html'
    contexto = {}
    obj = Inplace.objects.values('user_created').annotate(dcount=Count('user_created'))
    users = User.objects.all()
    
   
       
    if not obj:
        return HttpResponse('Registro no encontrado' + str(id))

    if request.method == 'GET':
        contexto = {'obj': obj, 'users':users}

    if request.method == 'POST':
        
        cdate = request.POST.get('created_date') 
        user_id = request.POST.get('user') 
        # print(cdate)
        # print(user_id)

        route = Inplace.objects.filter(datetime_insitu__startswith=cdate, user_created=user_id).all().order_by('datetime_insitu')
        table_origin = []
        table_destination = []
        table_route = []
        # print(route)
        for x in range(len(route) - 1):
            table_origin.append(route[x])
            
        for x in range(1, len(route) ):
            table_destination.append(route[x])
        
        for y in range(len(table_origin)):
            objeto = {}
            objeto['origin'] = table_origin[y].product
            objeto['origin_date'] = table_origin[y].datetime_insitu
            objeto['destination'] = table_destination[y].product
            objeto['destination_date'] = table_destination[y].datetime_insitu

            objeto['diferencia'] = table_destination[y].datetime_insitu - table_origin[y].datetime_insitu
            # print(table_destination[y].datetime_insitu - table_origin[y].datetime_insitu)
            table_route.append(objeto)

        user = User.objects.get(pk=user_id)
        cdate_date = datetime.strptime(cdate, "%Y-%m-%d")

        contexto = {'obj': obj, 'users':users, 'table_route':table_route, 'user':user, 'cdate':cdate_date}
        # return HttpResponse('Registro  visto')

    return render(request, template_name, contexto)

rondas/templates/rondas/inplace_form.html
{% extends 'base/base.html' %}

{% block page_content %}

<form method="POST" class="form-group" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="col-xl-12 col-md-12 mb-12">

        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
            {% else %}

            <div class="card border-left-primary shadow h-100 py-2">
                {% endif %}

                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                {% if obj %} Editar {% else %} Nuevo {% endif %} Video
                            </div>
                            <small class="text-danger">
                                {% if form.errors %}
                                {% for field in form %}
                                {% if field.errors %}
                                {% for error in field.errors %}
                                {{ error|escape }}
                                {% endfor %}
                                {% endif %}
                                {% endfor %}

                                {% if form.non_field_errors%}
                                {% for error in form.non_field_errors %}
                                {{ error|escape }}
                                {% endfor %}
                                {% endif %}
                                {% endif %}
                            </small>
                            <div class="dropdown-divider"></div>
                            <div class="form-group row">
                                <label for="id_latitude" class="col-sm-1 col-form-label">Latitud</label>
                                <div class="col-sm-3 ">
                                    <input type="text" name="latitude" maxlength="50" class="form-control"  readonly
                                        autocomplete="off" id="id_latitude" value="{% if obj %} {{obj.latitude}} {% endif %}">
                                </div>
                                <label for="id_longitude" class="col-sm-1 col-form-label">Longitud</label>
                                <div class="col-sm-3 ">
                                    <input type="text" name="longitude" maxlength="50" class="form-control" readonly
                                        autocomplete="off" id="id_longitude" value="{% if obj %} {{obj.longitude}} {% endif %}">
                                </div>
                                <label for="id_datetime_insitu" class="col-sm-1 col-form-label">Fecha de registro</label>
                                <div class="col-sm-3 ">
                                    <input type="datetime" name="datetime_insitu" class="form-control" id="id_datetime_insitu" readonly
                                        value="{% if obj %}{{obj.datetime_insitu|date:'Y-m-d'}}{% endif %}">
                                </div>
                               
                            </div>


                            <div class="form-group row">
                                <label for="id_contract" class="col-sm-2 col-form-label">Producto</label>
                                <div class="col-sm-10">
                                    <!-- <select name="category" id="id_category" required class="form-control">
                                        <option value="" selected>---------</option>
                                        
                                    </select> -->
                                    {{ form.product}}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_img" class="col-sm-2 col-form-label">Imagen</label>
                                <div class="col-sm-10">
                                    <input type="file" name="img" maxlength="300" class="form-control-file"
                                        accept="image/*" id="id_img" value="{% if obj %} {{obj.img}} {% endif %}">
                                </div>
                            </div>
                            
                            <!-- para mostrar video -->
                            <!-- <div class="form-group row ">
                                <div class="embed-responsive embed-responsive-21by9">

                                    <video width="320" height="240" controls class="embed-responsive-item" id="video_rep">
                                        <source type="video/mp4" src="" id="video_local">
                                    </video>
                                </div>
                            </div> -->




                            
                            <!-- <div class="form-group row">
                                <label for="id_video" class="col-sm-2 col-form-label">Video</label>
                                <div class="col-sm-10">
                                    <input type="file" name="video" maxlength="300" class="form-control-file"
                                        accept="video/*" id="id_video" value="{% if obj %} {{obj.video}} {% endif %}">
                                </div>
                            </div> -->
                            <div class="form-group row">
                                <div class="col-sm-2">Estado</div>
                                <div class="col-sm-10">
                                    <div class="form-check">
                                        <input type="checkbox" name="state" class="form-check-input" {% if obj.state == True %}
                                            checked {% endif %} id="id_state">
                                        <label class="form-check-label" for="id_state">
                                            Marcar estado.
                                        </label>
                                    </div>

                                </div>
                            </div>





                            <!-- {{form.as_p}} -->

                            <div class="dropdown-divider"></div>
                            <div class="form-group row text-center">
                                <div class="col-sm-12">
                                    <a href="{% url 'rondas:rondas_list' %}" class="btn btn-danger"><span
                                            class="fa fa-undo"> Cancelar</span></a>
                                    <button type="submit" class="btn btn-success"><span class="fa fa-save"></span>
                                        Guardar</button>
                                </div>
                            </div>
                            <!-- <button type="button" id="sacar_tiempo">sacr</button> -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>

{% endblock %}
{% block js_page %}
<script>
    $(document).ready(function () {
        $('#id_product').select2({ placeholder: "Seleccione", allowClear: true });

        $('#id_state').prop("checked", true);

        // ==============================================
        // var output = document.getElementById('map');

			// Verificar si soporta geolocalizacion
			if (navigator.geolocation) {
                console.log('soprtado para geolocalizacion')
				// mensaje('Tu dispositivo soporta Geolocalizacion','green');
			} else {
				// output.innerHTML = "<p></p>";
                mensaje('Tu dispositivo no soporta Geolocalizacion','red');
			}

			//Obtenemos latitud y longitud
			function localizacion(posicion) {

				var latitude = posicion.coords.latitude;
				var longitude = posicion.coords.longitude;

                $('#id_latitude').val(latitude);
                $('#id_longitude').val(longitude);


				console.log(latitude + ' - ' + longitude)

			}

			function error() {
				mensaje('No se pudo obtener tu ubicacion','red');

			}

			navigator.geolocation.getCurrentPosition(localizacion, error);

        var hoy = new Date();
        var fecha = hoy.getDate() + '/' + (hoy.getMonth() + 1) + '/'+ hoy.getFullYear();
        var hora = hoy.getHours() + ':' + hoy.getMinutes() +':'+ hoy.getSeconds();
        var datetime_insitu = fecha + ' ' + hora;
        $('#id_datetime_insitu').val(datetime_insitu);



    })


</script>

{% endblock %}

rondas/templates/rondas/inplace_list.html
{% extends 'base/base.html' %}

{% block page_content %}

<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de registros de visitas a locaciones</h6>
        {% if perms.rondas.delete_inplace %}
        <a class="btn btn-sm btn-outline-primary" href="{% url 'rondas:routes_view' %}">Revision de rutas</a>
        {% endif %}
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'rondas:ronda_new' %}">Nuevo visita en locacion</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hay videos registrados</div>

        {% else %}
        <div class="table-responsive">

            <table class="table table-striped table-hover table-bordered table-sm">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Usuario</th>
                        <th>Fecha</th>
                        <th>Producto</th>

                        <!-- <th>Imagen</th> -->
                        <th>Latitud</th>
                        <th>Longitud</th>

                        <th class="all">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in obj %}


                    <tr>
                        <td>{{ item.id }}</td>

                        <td>{{ item.user_created }}</td>
                        <td>{{ item.datetime_insitu}}</td>
                        <td>{{ item.product}}</td>
                        <!-- <td class="text-center">
                            {% if item.img %}
                            <img src="{{ item.img.url }}" class="img-thumbnail" alt="IMG" width="60" height="60">

                            {% endif %} -->
                        </td>
                        <td>{{ item.latitude }}</td>
                        <td>{{ item.longitude }}</td>



                        <td>
                            <!-- <a href="{% url 'content:video_edit' item.id %}"
                                class="btn btn-sm btn-outline-info btn-circle" role="button"><i
                                    class="far fa-edit"></i></a> -->
                            <button class="btn btn-sm btn-outline-primary btn-circle"
                                onclick="return abrir_modal('{% url 'rondas:ronda_view' item.id %}')"><i
                                    class="fas fa-map-marked-alt"></i></button>
                            <button class="btn btn-sm btn-outline-success btn-circle"
                                onclick="return abrir_modal('{% url 'rondas:ronda_view_image' item.id %}')"><i
                                    class="far fa-image"></i></button>
                            {% if perms.rondas.delete_inplace %}
                            <button class="btn btn-sm btn-outline-danger btn-circle"
                                onclick="return abrir_modal('{% url 'rondas:ronda_delete' item.id %}')"><i
                                    class="far fa-trash-alt"></i></button>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}


{% block js_page %}
<script>
    $(document).ready(function () {
        $('.table').DataTable();
    })
</script>


{% endblock %}

rondas/templates/rondas/inplace_view_image.html
<div class="modal-dialog modal-dialog-centered modal-xl ">
    <div class="modal-content">

        <form method="POST" class="form-group">
            {% csrf_token %}

            <div class="col-xl-12 col-md-12 mb-12">

                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div>
                                {% if obj.img %}
                                <img src="{{ obj.img.url }}" class="img-fluid" alt="Responsive image">
                                {% else %}
                                <h5>No se encontro imagen</h5>
                                {% endif %}
                            </div>


                            <div class="modal-footer">

                                <button type="button" class="btn btn-success"
                                    onclick="return cerrar_modal()">Aceptar</button>

                            </div>


                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>